# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\"9\n\x0c\x45mailMessage\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\x1f\n\rEmailResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2:\n\x0c\x45mailService\x12*\n\tSendEmail\x12\r.EmailMessage\x1a\x0e.EmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILMESSAGE']._serialized_start=15
  _globals['_EMAILMESSAGE']._serialized_end=72
  _globals['_EMAILRESPONSE']._serialized_start=74
  _globals['_EMAILRESPONSE']._serialized_end=105
  _globals['_EMAILSERVICE']._serialized_start=107
  _globals['_EMAILSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
