# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab13.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lab13.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blab13.proto\x12\x05lab13\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\" \n\rTokenResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x10\x42irthDateRequest\x12\x12\n\nbirth_date\x18\x01 \x01(\t\"\x1a\n\x0b\x41geResponse\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\"\x1c\n\x0cWordsRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\rWordsResponse\x12\x13\n\x0bsorted_text\x18\x01 \x01(\t2\xc3\x01\n\x0bTaskService\x12?\n\x12GenerateResetToken\x12\x13.lab13.EmailRequest\x1a\x14.lab13.TokenResponse\x12;\n\x0c\x43\x61lculateAge\x12\x17.lab13.BirthDateRequest\x1a\x12.lab13.AgeResponse\x12\x36\n\tSortWords\x12\x13.lab13.WordsRequest\x1a\x14.lab13.WordsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab13_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILREQUEST']._serialized_start=22
  _globals['_EMAILREQUEST']._serialized_end=51
  _globals['_TOKENRESPONSE']._serialized_start=53
  _globals['_TOKENRESPONSE']._serialized_end=85
  _globals['_BIRTHDATEREQUEST']._serialized_start=87
  _globals['_BIRTHDATEREQUEST']._serialized_end=125
  _globals['_AGERESPONSE']._serialized_start=127
  _globals['_AGERESPONSE']._serialized_end=153
  _globals['_WORDSREQUEST']._serialized_start=155
  _globals['_WORDSREQUEST']._serialized_end=183
  _globals['_WORDSRESPONSE']._serialized_start=185
  _globals['_WORDSRESPONSE']._serialized_end=221
  _globals['_TASKSERVICE']._serialized_start=224
  _globals['_TASKSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
