# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lab13_pb2 as lab13__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lab13_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResetToken = channel.unary_unary(
                '/lab13.TaskService/GenerateResetToken',
                request_serializer=lab13__pb2.EmailRequest.SerializeToString,
                response_deserializer=lab13__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.CalculateAge = channel.unary_unary(
                '/lab13.TaskService/CalculateAge',
                request_serializer=lab13__pb2.BirthDateRequest.SerializeToString,
                response_deserializer=lab13__pb2.AgeResponse.FromString,
                _registered_method=True)
        self.SortWords = channel.unary_unary(
                '/lab13.TaskService/SortWords',
                request_serializer=lab13__pb2.WordsRequest.SerializeToString,
                response_deserializer=lab13__pb2.WordsResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SortWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResetToken,
                    request_deserializer=lab13__pb2.EmailRequest.FromString,
                    response_serializer=lab13__pb2.TokenResponse.SerializeToString,
            ),
            'CalculateAge': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAge,
                    request_deserializer=lab13__pb2.BirthDateRequest.FromString,
                    response_serializer=lab13__pb2.AgeResponse.SerializeToString,
            ),
            'SortWords': grpc.unary_unary_rpc_method_handler(
                    servicer.SortWords,
                    request_deserializer=lab13__pb2.WordsRequest.FromString,
                    response_serializer=lab13__pb2.WordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab13.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lab13.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab13.TaskService/GenerateResetToken',
            lab13__pb2.EmailRequest.SerializeToString,
            lab13__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateAge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab13.TaskService/CalculateAge',
            lab13__pb2.BirthDateRequest.SerializeToString,
            lab13__pb2.AgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SortWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab13.TaskService/SortWords',
            lab13__pb2.WordsRequest.SerializeToString,
            lab13__pb2.WordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
